Resolve downloading label issue
MatthewFrench/LeagueSandboxAutoSetup pull request #16
Opened 2021-06-12 17:44 UTC by Kipero

Resolve #15

2021-06-12 17:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LeagueSandbox/LeagueSandboxAutoSetup?pullRequest=16) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LeagueSandbox/LeagueSandboxAutoSetup?pullRequest=16) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LeagueSandbox/LeagueSandboxAutoSetup?pullRequest=16) it.</sub>

2021-06-12 17:46 UTC, Kipero commented
![image](https://user-images.githubusercontent.com/27647817/121784878-d7cdb080-cbb6-11eb-8f64-fcc75e6c2f6f.png)

2021-06-12 17:48 UTC, microsoftv requested changes
Some unused events.

2021-06-13 15:36 UTC, danil179 requested changes
Remove unused code.

2021-06-13 15:36 UTC, danil179 commented on League Sandbox Auto Setup/leagueSandboxAutoSetupForm.cs
> +        private void cloningProgressLabel_Click(object sender, EventArgs e)
Delete this and its corresponding event. If you think that these are important please add `TODO:` that explains what is planned here.

2021-06-13 15:36 UTC, danil179 commented on League Sandbox Auto Setup/leagueSandboxAutoSetupForm.cs
> +        private void downloadingProgressLabel_Click(object sender, EventArgs e)
Delete this and its corresponding event. If you think that these are important please add `TODO:` that explains what is planned here.

2021-06-14 17:13 UTC, danil179 approved these changes
Approved.

2021-06-14 17:14 UTC, merged